### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by bnhanson1287** [bnhanson1287/DMIT-2018-Workbook#2]
Create a page that shows our suppliers and the products they offer. I will need to see the information in the following "structure".

- **Supplier:**
 - Company Name
 - Phone Number
-  **Product Summary:**
   - Product Name
   - Category Name
   - Unit Price
   - Quantity / Unit

[//]: # (Hello)
### TASKS
- [x] Create LINQ query with LinqPad
- [x] Create classes for the _Read Model_
- [x] Copy/Adapt LinqPad query to BLL method
- [x] Create page with nested repeater
